#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from chesttimer.db.rooster import Rooster
from chesttimer.db.rooster import Character

personal = Rooster('./personal.json')

personal.add(Character('Brigadier Buzzkill', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.male,
                       profession=Character.Professions.elementalist,
                       disciplines=None,
                       order=None))
personal.add(Character('Warlord Buzzkill', level=4,
                       race=Character.Races.sylvari,
                       sex=Character.Sex.female,
                       profession=Character.Professions.guardian,
                       disciplines=None,
                       order=None))
personal.add(Character('Thorianar', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.male,
                       profession=Character.Professions.guardian,
                       disciplines={Character.Disciplines.armorsmith: 500,
                                    Character.Disciplines.weaponsmith: 429},
                       order=Character.Orders.durmand_priori))
personal.add(Character('Commander Buzzkill', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.male,
                       profession=Character.Professions.engineer,
                       disciplines={Character.Disciplines.huntsman: 500,
                                    Character.Disciplines.leatherworker: 500},
                       order=Character.Orders.durmand_priori))
personal.add(Character('Shayeera Tombstone', level=80,
                       race=Character.Races.norn,
                       sex=Character.Sex.female,
                       profession=Character.Professions.guardian,
                       disciplines={Character.Disciplines.artificer: 414,
                                    Character.Disciplines.huntsman: 196},
                       order=Character.Orders.order_of_whispers))
personal.add(Character('Sgt Buzzkill', level=25,
                       race=Character.Races.human,
                       sex=Character.Sex.female,
                       profession=Character.Professions.warrior,
                       disciplines=None,
                       order=None))
personal.add(Character('Triearch Buzzkill', level=25,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.guardian,
                       disciplines=None,
                       order=None))
personal.add(Character('Captain Buzzkill', level=25,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.guardian,
                       disciplines=None,
                       order=None))
personal.add(Character('Dark Tombstone', level = 15,
                       race=Character.Races.charr,
                       sex=Character.Sex.male,
                       profession=Character.Professions.mesmer,
                       disciplines=None,
                       order=None))
personal.add(Character('Taxiarhos Buzzkill', level=34,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.ranger,
                       disciplines=None,
                       order=None))
personal.add(Character('Legionnare Buzzkill', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.engineer,
                       disciplines=None,
                       order=None))
personal.add(Character('Praetor Buzzkill', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.necromancer,
                       disciplines={Character.Disciplines.tailor: 400},
                       order=None))
personal.add(Character('Orion The Ox', level=33,
                       race=Character.Races.asura,
                       sex=Character.Sex.male,
                       profession=Character.Professions.guardian,
                       disciplines=None,
                       order=Character.Orders.vigil))
personal.add(Character('Hawket Joomp', level=31,
                       race=Character.Races.sylvari,
                       sex=Character.Sex.male,
                       profession=Character.Professions.ranger,
                       disciplines={Character.Disciplines.huntsman: 250},
                       order=Character.Orders.vigil))
personal.add(Character('Thorielie', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.thief,
                       disciplines={Character.Disciplines.artificer: 171},
                       order=None))
personal.add(Character('Dianna Tombstone', level=80,
                       race=Character.Races.norn,
                       sex=Character.Sex.female,
                       profession=Character.Professions.elementalist,
                       disciplines={Character.Disciplines.chef: 400},
                       order=Character.Orders.order_of_whispers))
personal.add(Character('Shayera Tombstone', level=80,
                       race=Character.Races.charr,
                       sex=Character.Sex.female,
                       profession=Character.Professions.warrior,
                       disciplines={Character.Disciplines.chef: 341,
                                    Character.Disciplines.jeweler: 400},
                       order=None))
personal.add(Character('Mike Horner', level=23,
                       race=Character.Races.human,
                       sex=Character.Sex.male,
                       profession=Character.Professions.guardian,
                       disciplines=None,
                       order=None))
personal.add(Character('Legatus Buzzkill', level=20,
                       race=Character.Races.sylvari,
                       sex=Character.Sex.female,
                       profession=Character.Professions.engineer,
                       disciplines=None,
                       order=None))
personal.add(Character('Tina Tyler', level=21,
                       race=Character.Races.norn,
                       sex=Character.Sex.female,
                       profession=Character.Professions.engineer,
                       disciplines=None,
                       order=None))
personal.add(Character('Private Buzzkill', level=21,
                       race=Character.Races.human,
                       sex=Character.Sex.female,
                       profession=Character.Professions.engineer,
                       disciplines=None,
                       order=None))
personal.add(Character('Tom Byron', level=20,
                       race=Character.Races.norn,
                       sex=Character.Sex.male,
                       profession=Character.Professions.guardian,
                       disciplines=None,
                       order=None))
personal.save()
